$(document).ready(function(){var SURFACE_WATER_ZONE=7,GEOCLIENT_URL="//maps.nyc.gov/geoclient/v1/search.json?app_key=17AFAE4AA01BB4EB3&app_id=mental-health",GOOGLE_URL="https://maps.googleapis.com/maps/api/js?key=AIzaSyBB0m1-hNGz_za3-BpD3uoc6JqwITWI_xg&channel=mental-health&sensor=false&libraries=visualization",MESSAGES={facility_info_field:'<div class="${css} notranslate" translate="no">${value}</div>',facility_info_web:'<li class="inf-web"><div><a href="${web}" target="_blank">${web}</a></div>&nbsp;</li>',
facility_info_phone:'<a class="inf-phone" data-role="button" href="tel:${href}" ${target}>${text}</a>',facility_distance:'<div class="inf-dist">&#8226; ${distance} miles &#8226;</div>',facility_info_map:'<a class="capitalize inf-map" data-role="button" onclick=\'nyc.app.zoomFacility("${id}");\'>map</a>',facility_info_dir:'<a class="capitalize inf-dir" data-role="button" onclick=\'nyc.app.direct("${id}");\'>directions</a>',facility_info_detail:'<a class="capitalize inf-detail" data-role="button" onclick="nyc.app.details(this);">details</a>',
facility_info_eligibility:"Call to confirm eligibility ",facility_info_resident:'<li class="inf-res">${note}</li>',facility_info_in_patient:'<li class="inf-in">${note}</li>',facility_tip:'<div class="${css}">${name}</div>',bad_input:"The location you entered was not understood",data_load_error:"There was a problem loading map data. Please refresh the page to try again.",data_filter_warn:"There are no facilities that meet the criteria of the applied filters.  Please modify your filter choices.",copyright:"&copy; ${yr} City of New York",
lifenet_word:"1-800-LIFENET",lifenet_number:"(1-800-543-3638)",lifenet_word_es:"1-877-AYUDESE",lifenet_number_es:"(1-877-990-8585)",lifenet_word_ko:"1-877-990-8585",facility_vcard:'<a class="capitalize inf-vcard ${css}" data-role="button" onclick="nyc.app.vcard(this);" data-feature-id="${id}" data-ios="${ios}">add contact</a>',note_in_patient:"This may be an inpatient service provider. (A 24/7 hospital-based program for treatment of a person who can not be adequately served in the community.)",note_resident:"This may be an residential treatment service provider. (A 24-hour program which houses individuals in the community and provides a supervised, therapeutic environment, which seeks to develop the resident's skills and capacity to live in the community and attend school/ work as appropriate.)",
note_download:"This contact was downloaded from https://maps.nyc.gov/mental-health/",type_age:"Age groups: ",type_care:"Types of care: ",type_insurance:"Types of insurance: ",type_demographic:"Demographics: "},LANGUAGES={en:{val:"English",desc:"English",hint:"Translate"},ar:{val:"Arabic",desc:"&#x627;&#x644;&#x639;&#x631;&#x628;&#x64A;&#x629;",hint:"&#x62A;&#x631;&#x62C;&#x645;"},bn:{val:"Bengali",desc:"&#x9AC;&#x9BE;&#x999;&#x9BE;&#x9B2;&#x9BF;",hint:"&#x985;&#x9A8;&#x9C1;&#x9AC;&#x9BE;&#x9A6; &#x995;&#x9B0;&#x9BE;"},
"zh-CN":{val:"Chinese (Simplified)",desc:"&#x4E2D;&#x56FD;",hint:"&#x7FFB;&#x8BD1;"},fr:{val:"French",desc:"Fran&#231;ais",hint:"Traduire"},ht:{val:"Haitian Creole",desc:"Krey&#242;l Ayisyen",hint:"Tradui"},ko:{val:"Korean",desc:"&#xD55C;&#xAD6D;&#xC758;",hint:"&#xBC88;&#xC5ED;"},ru:{val:"Russian",desc:"P&#x443;&#x441;&#x441;&#x43A;&#x438;&#x439;",hint:"&#x43F;&#x435;&#x440;&#x435;&#x432;&#x435;&#x441;&#x442;&#x438;"},es:{val:"Spanish",desc:"Espa&#241;ol",hint:"Traducir"},ur:{val:"Urdu",desc:"&#x627;&#x631;&#x62F;&#x648;",
hint:"&#x62A;&#x631;&#x62C;&#x645;&#x6C1; &#x6A9;&#x631;&#x6CC;&#x6BA;"}},FEATURE_DECORATIONS={fieldAccessors:{getCoordinates:function(){var g=this.getGeometry();return g?g.getCoordinates():null},getName:function(){return this.get("name_1")},getName2:function(){return this.get("name_2")},getAddress:function(){return this.getAddress1()+", "+this.getAddress3()},getAddress1:function(){return this.get("street_1")},getAddress2:function(){return this.get("street_2")},getCity:function(){return this.capitalize(this.get("city"))},
getZip:function(){return this.get("zip")},getAddress3:function(){return this.getCity()+", NY "+this.getZip()},getPhoneText:function(){var phone=this.get("phone").replace(/[\(\-\s\x]/g,"");if(phone.substr(0,1)=="1")phone=phone.substr(1);if(phone.length==10)phone=phone.replace(/(\w{3})(\w{3})(\w{4})/,"($1) $2-$3");else if(phone.length>10)phone=phone.replace(/(\w{3})(\w{3})(\w{4})/,"($1) $2-$3 ");else phone="";return phone},getPhoneNumber:function(){var phone=this.get("phone").replace(/[\(\)\-\s\x]/g,
"");if(phone.substr(0,1)=="1")phone=phone.substr(1);if(phone.length>10)phone=phone.replace(/(\w{3})(\w{3})(\w{4})(\w*)/,"$1-$2-$3,$4");else phone=phone.replace(/(\w{3})(\w{3})(\w{4})/,"$1-$2-$3");return"+1-"+phone},getWeb:function(){return this.get("website")},isInPatient:function(){return this.get("filter_inpatient_svc")==1},isResidential:function(){return this.get("filter_residential_pgm")==1},isIos:function(){return navigator.userAgent.match(/(iPad|iPhone|iPod|iOS)/g)},capitalize:function(s){var words=
s.split(" "),result="";$.each(words,function(i,w){var word=w.toLowerCase();result+=word.substr(0,1).toUpperCase();result+=word.substr(1).toLowerCase();result+=" "});return result.trim()},vCardData:function(){var coords=proj4("EPSG:2263","EPSG:4326",this.getCoordinates()),orgs=[this.getName()],note=[this.message("facility_info_eligibility")],svcTypes=this.getServiceTypes(),data={};for(var type in svcTypes){var types=svcTypes[type];if(types.length){var typeNote=this.message("type_"+type);$.each(types,
function(i,type){var comma=i<types.length-1?", ":"";typeNote+=type+comma});note.push(typeNote)}}if(this.getName2())orgs.push(this.getName2());if(this.isInPatient())note.push(this.message("note_in_patient"));if(this.isResidential())note.push(this.message("note_resident"));note.push(this.message("note_download"));data.organization=orgs;data.orgType="Meantal health service provider";data.address1=this.getAddress1();data.address2=this.getAddress2();data.city=this.getCity();data.state="NY";data.zip=this.getZip();
data.phone=this.getPhoneNumber();data.url=this.getWeb();data.note=note;if(!this.isIos()){data.longitude=coords[0];data.latitude=coords[1]}return data},getAgeTypes:function(){var types=[];if(this.get("flag_chld"))types.push("Children & Adolescents (17 and younger)");if(this.get("flag_yad"))types.push("Young Adults (18-25)");if(this.get("flag_adlt"))types.push("Adults (26-64)");if(this.get("flag_snr"))types.push("Seniors (65 or older)");return types},getCareTypes:function(){var types=[];if(this.get("flag_mhf"))types.push("Mental Health");
if(this.get("flag_saf"))types.push("Substance Use");return types},getInsuranceTypes:function(){var types=[];if(this.get("flag_mc"))types.push("Medicare");if(this.get("flag_md"))types.push("Medicaid");if(this.get("flag_si"))types.push("CHP/FHP/Essential");if(this.get("flag_pi"))types.push("Private");if(this.get("flag_np_ss"))types.push("No insurance");return types},getDemographicTypes:function(){var types=[];if(this.get("filter_military"))types.push("Military-Affiliated");if(this.get("flag_gl"))types.push("LGBTQ Community");
if(this.get("flag_pw"))types.push("Pregnant/postpartum women");if(this.get("flag_dv"))types.push("Intimate Partner Violence Survivors");if(this.get("flag_hv"))types.push("HIV/AIDS Community");return types},getServiceTypes:function(){return{age:this.getAgeTypes(),care:this.getCareTypes(),insurance:this.getInsuranceTypes(),demographic:this.getDemographicTypes()}}},htmlRenderer:{html:function(renderFor){var id=this.getId(),div=$("<div></div>"),result=$("<div></div>");result.append(div);div.addClass(renderFor).addClass("inf-facility").append(this.message("facility_info_field",
{css:"inf-name",value:this.getName()})).append(this.message("facility_info_field",{css:"inf-name",value:this.getName2()})).append(this.message("facility_info_field",{css:"inf-addr",value:this.getAddress1()})).append(this.message("facility_info_field",{css:"inf-addr",value:this.getAddress2()})).append(this.message("facility_info_field",{css:"inf-addr",value:this.getAddress3()}));this.phoneGrp(div);this.mapGrp(div,id);if(!isNaN(this.getDistance()))div.prepend(this.message("facility_distance",{distance:(this.getDistance()/
5280).toFixed(2)}));return result.html()},vCardBtn:function(css){return this.message("facility_vcard",{id:this.getId(),ios:this.isIos()?"1":"",css:css})},phoneGrp:function(div){var html="",css="";if(this.getPhoneText())html=this.message("facility_info_phone",{text:this.getPhoneText(),href:this.getPhoneNumber()});else css="vcard-big";div.append(this.buttonGrp("grp-phone",html+this.vCardBtn(css)))},mapGrp:function(div,id){var group=this.buttonGrp("grp-map",this.message("facility_info_map",{id:id})+
this.message("facility_info_dir",{id:id}));this.details(div,group);div.append(group)},buttonGrp:function(css,html){var group=$('<div class="btn-grp" data-role="controlgroup" data-type="horizontal"></div>');group.addClass(css);group.append(html);return group},details:function(div,group){var web=this.getWeb(),svcTypes=this.getServiceTypes(),ul=$("<ul></ul>");group.append(this.message("facility_info_detail"));div.append(ul);if(web)ul.append(this.message("facility_info_web",{web:web}));ul.append("<li><b>"+
this.message("facility_info_eligibility")+"</b></li>");for(var type in svcTypes){var types=svcTypes[type];if(types.length){var li=$("<li><b>"+this.message("type_"+type)+"</b> </li>");ul.append(li);$.each(types,function(i,type){var comma=i<types.length-1?", ":"";li.append(type+comma)})}}if(this.isInPatient())ul.append(this.message("facility_info_in_patient",{note:this.message("note_in_patient")}));if(this.isResidential())ul.append(this.message("facility_info_resident",{note:this.message("note_resident")}))}}};
var content=new nyc.Content(MESSAGES);new nyc.Share("#map","http://www1.nyc.gov/nyc-resources/mental-health-finder-form.page");var map=new ol.Map({target:$("#map")[0],layers:[new nyc.ol.layer.BaseLayer],view:new ol.View({projection:nyc.EPSG_2263,resolutions:nyc.ol.layer.BaseLayer.RESOLUTIONS})});map.getView().fit(nyc.EXTENT,map.getSize());var lang=new nyc.Lang("#translate-container",LANGUAGES);nyc.app=new nyc.App(map,"https://data.cityofnewyork.us/api/views/8nqg-ia7v/rows.csv?accessType=DOWNLOAD",
FEATURE_DECORATIONS,content,new nyc.Style,new nyc.ol.control.ZoomSearch(map),new nyc.ol.Locate(new nyc.Geoclient(GEOCLIENT_URL),nyc.EPSG_2263,nyc.EXTENT),new nyc.Directions("#dir-map","#directions",GOOGLE_URL),new nyc.ol.Popup(map),new nyc.Pager,lang)});window.nyc=window.nyc||{};proj4.defs("EPSG:2263","+proj=lcc +lat_1=41.03333333333333 +lat_2=40.66666666666666 +lat_0=40.16666666666666 +lon_0=-74 +x_0=300000.0000000001 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=ft +to_meter=0.3048006096012192 +no_defs");nyc.EXTENT=[912090,119053,1068317,273931];nyc.EPSG_2263=ol.proj.get("EPSG:2263");nyc.CENTER=[990203,196492];nyc.EventHandling=function(){};
nyc.EventHandling.prototype={on:function(eventName,evtHdlr,hdlrScope){this.addHdlr(eventName,evtHdlr,hdlrScope)},one:function(eventName,evtHdlr,hdlrScope){this.addHdlr(eventName,evtHdlr,hdlrScope,true)},addHdlr:function(eventName,evtHdlr,hdlrScope,one){this.evtHdlrs=this.evtHdlrs||{};this.evtHdlrs[eventName]=this.evtHdlrs[eventName]||[];this.evtHdlrs[eventName].push({handler:evtHdlr,scope:hdlrScope,remove:one})},trigger:function(eventName,data){this.evtHdlrs=this.evtHdlrs||{};var handlers=this.evtHdlrs[eventName],
remove=[];if(handlers){$.each(handlers,function(index,hdlr){if(hdlr.scope)hdlr.handler.call(hdlr.scope,data);else hdlr.handler(data);if(hdlr.remove)remove.push(hdlr)});$.each(remove,function(_,hdlr){handlers.splice($.inArray(hdlr,handlers),1)})}},off:function(eventName,evtHdlr,hdlrScope){this.evtHdlrs=this.evtHdlrs||{};var handlers=this.evtHdlrs[eventName];$.each(handlers,function(index,hdlr){if(hdlr.handler===evtHdlr&&hdlr.scope===hdlrScope){handlers.splice(index,1);return false}})}};
nyc.inherits=function(childCtor,parentCtor){for(var member in parentCtor.prototype)if(!(member in childCtor.prototype))childCtor.prototype[member]=parentCtor.prototype[member]};window.nyc=window.nyc||{};nyc.Content=function(){var contentClass=function(messages){this.messages=messages};contentClass.prototype={messages:null,message:function(msgId,values){var result=this.messages[msgId];for(var val in values)result=result.replace(new RegExp("\\$\\{"+val+"\\}","g"),values[val]);return result}};return contentClass}();window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.control=nyc.ol.control||{};
nyc.ol.control.ZoomSearch=function(map){var me=this;$(map.getTarget()).append(nyc.ol.control.ZoomSearch.HTML).trigger("create");map.addControl(new ol.control.Control({element:$("#ctl-z-srch")[0]}));me.map=map;me.view=map.getView();me.input=$("#fld-srch-container input");me.list=$("#fld-srch");me.input.on("keyup change",$.proxy(me.key,me));$("#btn-z-in, #btn-z-out").click($.proxy(me.zoom,me));$("#fld-srch-container .ui-input-clear").click(function(){me.list.slideUp()});$("#srch-type-addr").click(function(){me.val("");
me.input.focus()});$("#btn-geo").click(function(){me.val("");me.trigger(nyc.ol.control.ZoomSearch.EventType.GEOLOCATE)})};
nyc.ol.control.ZoomSearch.prototype={map:null,zoom:function(e){var view=this.view;this.map.beforeRender(ol.animation.zoom({resolution:view.getResolution()}));view.setZoom(view.getZoom()+$(e.target).data("zoom-incr"))},key:function(e){if(e.keyCode==13){this.triggerSearch();this.list.slideUp()}else this.list.slideDown()},triggerSearch:function(){var input=this.val().trim();if(input.length){this.input.blur();this.searching(true);this.trigger(nyc.ol.control.ZoomSearch.EventType.SEARCH,input)}},val:function(val){if(val){this.input.val(val);
this.searching(false)}return this.input.val()},disambiguate:function(possibleResults){var me=this;me.searching(false);if(possibleResults.length){me.list.empty();$.each(possibleResults,function(i,locateResult){var name=locateResult.name,li=$('<li class="ui-li-static ui-body-inherit srch-type-addr notranslate" translate="no">'+name+"</li>");me.list.append(li);li.click(function(){me.val(name);me.trigger(nyc.ol.control.ZoomSearch.EventType.DISAMBIGUATED,locateResult);li.parent().slideUp()})});me.list.slideDown()}},
searching:function(show){$("#fld-srch-container a.ui-input-clear")[show?"addClass":"removeClass"]("searching")}};nyc.inherits(nyc.ol.control.ZoomSearch,nyc.EventHandling);nyc.ol.control.ZoomSearch.EventType={SEARCH:"search",GEOLOCATE:"geolocate",DISAMBIGUATED:"disambiguated"};
nyc.ol.control.ZoomSearch.HTML='<div id="ctl-z-srch">'+'<div id="fld-srch-container" class="ctl">'+'<ul id="fld-srch" class="ui-corner-all" data-role="listview" data-filter="true" data-filter-reveal="true" data-filter-placeholder="Search for an address..."></ul>'+"</div>"+'<a id="btn-z-in" class="ctl ctl-btn" data-role="button" data-icon="plus" data-iconpos="notext" data-zoom-incr="1" title="Zoom in">'+'<span class="noshow">Zoom in</span>'+"</a>"+'<a id="btn-z-out" class="ctl ctl-btn" data-role="button" data-icon="minus" data-iconpos="notext" data-zoom-incr="-1" title="Zoom out">'+
"Zoom out"+"</a>"+'<a id="btn-geo" class="ctl ctl-btn" data-role="button" data-icon="none" data-iconpos="notext" title="Current location">'+"Zoom out"+"</a>"+'<ul id="fld-srch-retention"></ul>'+"</div>";window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.source=nyc.ol.source||{};nyc.ol.source.AcrGisCacheOptions;
nyc.ol.source.AcrGisCache=function(options){ol.source.TileImage.call(this,options);this.imageExtension=options.imageExtension;this.url=options.url?options.url:null;this.urls=options.urls?options.urls:[];this.urlIdx=0;this.defaultTileUrlFunction=function(tileCoord,pixelRatio,projection){var z="L"+this.pad(tileCoord[0].toString(),2),x="C"+this.pad(tileCoord[1].toString(),8),y="R"+this.pad((-tileCoord[2]-1).toString(),8);return this.nextUrl()+z+"/"+y+"/"+x+"."+this.imageExtension};this.pad=function(num,
len){var str=Number(num).toString(16);while(str.length<len)str="0"+str;return str};this.nextUrl=function(){if(this.urls.length){this.urlIdx=this.urlIdx<this.urls.length-1?this.urlIdx+1:0;return this.urls[this.urlIdx]+"/"}else return this.url+"/"};this.tileUrlFunction=options.tileUrlFunction||this.defaultTileUrlFunction};ol.inherits(nyc.ol.source.AcrGisCache,ol.source.TileImage);window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.source=nyc.ol.source||{};
nyc.ol.source.Decorating=function(options,decorationMixins){options=options||{};options.loader=options.loader||nyc.ol.source.Decorating.xhrLoader;this.featuresloaded=false;this.featureloaderror=false;this._url=options.url;this._format=options.format;this._xhrFeaturesLoaded=false;ol.source.Vector.call(this,options);this.on("addfeature",function(e){var feature=e.feature;$.each(decorationMixins,function(_,mixin){for(var memb in mixin)feature[memb]=mixin[memb]})})};
ol.inherits(nyc.ol.source.Decorating,ol.source.Vector);nyc.ol.source.Decorating.xhrLoader=function(extent,resolution,projection){var me=this;if(!me._xhrFeaturesLoaded&&me._url)$.ajax({url:me._url,dataType:"html",success:function(data){me.addFeatures(me._format.readFeatures(data,{featureProjection:projection}));me._xhrFeaturesLoaded=true;me.set("featuresloaded",true)},error:function(){me.set("featureloaderror",true)}})};nyc.ol.source.Decorating.prototype.isXhrFeaturesLoaded=function(){return this._xhrFeaturesLoaded};
nyc.ol.source.Decorating.LoaderEventType={FEATURESLOADED:"change:featuresloaded",FEATURELOADERROR:"change:featureloaderror"};window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.source=nyc.ol.source||{};nyc.ol.source.Filter;
nyc.ol.source.FilteringAndSorting=function(options,decorationMixins){var me=this;me.allFeatures=[];me.filtering=false;decorationMixins=decorationMixins||[];decorationMixins.push({getDistance:function(){return this.get("distance")},setDistance:function(distance){return this.set("distance",distance)}});nyc.ol.source.Decorating.call(this,options,decorationMixins);me.on("addfeature",function(e){if(!me.filtering)me.allFeatures.push(e.feature)});me.on("removefeature",function(e){var i=$.inArray(e.feature,
me.allFeatures);if(i>-1)me.allFeatures.splice(i,1)})};ol.inherits(nyc.ol.source.FilteringAndSorting,nyc.ol.source.Decorating);
nyc.ol.source.FilteringAndSorting.prototype.filter=function(filters){var me=this,filteredFeatures=[],filteredFeaturesMap={};$.each(me.allFeatures,function(_,f){var incl=true;$.each(filters,function(_,filter){incl=$.inArray(f.get(filter.property)+"",filter.values)>-1;if(!incl)return false});if(incl)if(!filteredFeaturesMap[f.getId()]){filteredFeaturesMap[f.getId()]=f;filteredFeatures.push(f)}});me.clear(true);me.filtering=true;me.addFeatures(filteredFeatures);me.filtering=false};
nyc.ol.source.FilteringAndSorting.prototype.sort=function(coordinate){var result=this.getFeatures();if(coordinate){$.each(result,function(_,facility){var center=ol.extent.getCenter(facility.getGeometry().getExtent()),line=new ol.geom.LineString([center,coordinate]);facility.setDistance(line.getLength())});result.sort(function(a,b){if(a.getDistance()<b.getDistance())return-1;if(a.getDistance()>b.getDistance())return 1;return 0})}return result};window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.layer=nyc.ol.layer||{};nyc.ol.layer.BaseLayer=function(options){ol.layer.Tile.call(this,options||nyc.ol.layer.BaseLayer.DEFAULT_OPTIONS)};ol.inherits(nyc.ol.layer.BaseLayer,ol.layer.Tile);nyc.ol.layer.BaseLayer.RESOLUTIONS=[434.027777777778,303.819444444444,222.222222222222,111.111111111111,55.5555555555556,27.7777777777778,13.8888888888889,6.94444444444444,3.47222222222222,1.73611111111111,.868055555555556];nyc.ol.layer.BaseLayer.ORIGIN=[7E5,44E4];
nyc.ol.layer.BaseLayer.EXTENT=[7E5,-4444.4444444447,1366666.6666667,44E4];nyc.ol.layer.BaseLayer.TILE_SIZE=512;nyc.ol.layer.BaseLayer.BASIC_URLS=["//maps.nyc.gov/gis/data/tiles/basic/","//maps1.nyc.gov/gis/data/tiles/basic/","//maps2.nyc.gov/gis/data/tiles/basic/","//maps3.nyc.gov/gis/data/tiles/basic/"];nyc.ol.layer.BaseLayer.ORTHO_URLS=["//maps.nyc.gov/gis/data/tiles/orthosLatest/","//maps1.nyc.gov/gis/data/tiles/orthosLatest/","//maps2.nyc.gov/gis/data/tiles/orthosLatest/","//maps3.nyc.gov/gis/data/tiles/orthosLatest/"];
nyc.ol.layer.BaseLayer.IMAGE_EXTENSION="jpg";nyc.ol.layer.BaseLayer.BASIC_OPTIONS={source:new nyc.ol.source.AcrGisCache({urls:nyc.ol.layer.BaseLayer.BASIC_URLS,imageExtension:nyc.ol.layer.BaseLayer.IMAGE_EXTENSION,projection:nyc.EPSG_2263,tileGrid:new ol.tilegrid.TileGrid({origin:nyc.ol.layer.BaseLayer.ORIGIN,extent:nyc.ol.layer.BaseLayer.EXTENT,resolutions:nyc.ol.layer.BaseLayer.RESOLUTIONS,tileSize:nyc.ol.layer.BaseLayer.TILE_SIZE})})};nyc.ol.layer.BaseLayer.DEFAULT_OPTIONS=nyc.ol.layer.BaseLayer.BASIC_OPTIONS;
nyc.ol.layer.BaseLayer.ORTHO_OPTIONS={source:new nyc.ol.source.AcrGisCache({urls:nyc.ol.layer.BaseLayer.ORTHO_URLS,imageExtension:nyc.ol.layer.BaseLayer.IMAGE_EXTENSION,projection:nyc.EPSG_2263,tileGrid:new ol.tilegrid.TileGrid({origin:nyc.ol.layer.BaseLayer.ORIGIN,extent:nyc.ol.layer.BaseLayer.EXTENT,resolutions:nyc.ol.layer.BaseLayer.RESOLUTIONS,tileSize:nyc.ol.layer.BaseLayer.TILE_SIZE})})};window.nyc=window.nyc||{};
nyc.Directions=function(){var dirClass=function(mapTarget,routeTarget,url){var me=this;me.mapTarget=mapTarget;me.routeTarget=routeTarget;me.url=(url||nyc.Directions.GOOGLE_URL)+"&callback=nyc.directions.setup";nyc.directions=me;$(".dir-mode-btn").click($.proxy(this.mode,this));$("#fld-from input").keypress(function(e){if(e.keyCode==13){me.args.from=$("#fld-from input").val();me.directions(me.args)}});$("#dir-toggle a").click(function(e){$("#dir-toggle a").removeClass("ui-btn-active");$(e.target).addClass("ui-btn-active");
$("#dir-panel").slideToggle()})};dirClass.prototype={map:null,service:null,renderer:null,args:null,modeBtn:"#mode-transit",directions:function(args){var me=this,mode=args.mode||"TRANSIT";me.args=args;if(!this.map){setTimeout(function(){$.getScript(me.url)},500);return}$("#fld-from input").val(args.from||"");$("#fld-to").html(args.to);$("#fld-facility").html(args.facility);if(args.from)this.service.route({origin:args.from,destination:args.to,travelMode:google.maps.TravelMode[mode]},function(response,
status){if(status==google.maps.DirectionsStatus.OK){var leg=response.routes[0].legs[0],addrA=leg.start_address.replace(/\, USA/,""),addrB=leg.end_address.replace(/\, USA/,"");me.renderer.setOptions({map:me.map,panel:$(me.routeTarget).get(0),directions:response});$("#fld-from input").val(addrA);$("#fld-to").html(addrB)}$(".dir-mode-btn").removeClass("active-mode");$(me.modeBtn).addClass("active-mode");setTimeout(function(){me.trigger(nyc.Directions.EventType.CHANGED,{response:response,status:status})},
200)})},setup:function(){this.map=new google.maps.Map($(this.mapTarget).get(0),{mapTypeId:google.maps.MapTypeId.ROADMAP,backgroundColor:"#D3D3D3",panControl:false,streetViewControl:false,mapTypeControl:false,zoomControl:false,maxZoom:18,styles:[{featureType:"administrative.country",stylers:[{visibility:"off"}]},{featureType:"administrative.province",stylers:[{visibility:"off"}]},{featureType:"administrative.land_parcel",stylers:[{visibility:"off"}]},{featureType:"landscape.man_made",stylers:[{visibility:"on"}]},
{featureType:"poi.attraction",stylers:[{visibility:"off"}]},{featureType:"poi.business",stylers:[{visibility:"off"}]},{featureType:"poi.place_of_worship",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"geometry",stylers:[{hue:"#A1D5F1"},{saturation:55},{lightness:13},{visibility:"on"}]},{featureType:"transit.line",stylers:[{visibility:"off"}]},{featureType:"road.arterial",elementType:"all",stylers:[{hue:"#d4d4d4"},{saturation:-100},{lightness:27},{visibility:"on"}]},{featureType:"road.local",
elementType:"all",stylers:[{hue:"#e8e8e8"},{saturation:-100},{lightness:-9},{visibility:"on"}]},{featureType:"road.highway",elementType:"all",stylers:[{hue:"#bababa"},{saturation:-100},{lightness:25},{visibility:"on"}]},{featureType:"poi.park",elementType:"all",stylers:[{hue:"#D6DDD5"},{saturation:-76},{lightness:32},{visibility:"on"}]},{featureType:"poi.school",elementType:"all",stylers:[{hue:"#DAD4C3"},{saturation:-51},{lightness:-2},{visibility:"on"}]}]});this.service=new google.maps.DirectionsService;
this.renderer=new google.maps.DirectionsRenderer;this.directions(this.args)},mode:function(e){this.args=this.args||{};this.modeBtn=e.target;this.args.mode=$(this.modeBtn).data("mode");this.directions(this.args)}};return dirClass}();nyc.inherits(nyc.Directions,nyc.EventHandling);nyc.Directions.EventType={CHANGED:"changed"};nyc.Directions.GOOGLE_URL="https://maps.googleapis.com/maps/api/js?&sensor=false&libraries=visualization";nyc.Directions.Args;window.nyc=window.nyc||{};nyc.Geocoder=function(){};nyc.Geocoder.Accuracy={HIGH:0,MEDIUM:100,LOW:1E3,ZIP_CODE:2E3};nyc.Geocoder.prototype.search=function(input){};nyc.Geoclient=function(url,projection){this.url=url+"&input=";this.projection=projection};
nyc.Geoclient.prototype={url:null,projection:null,project:function(coordinates){if(coordinates&&this.projection)return proj4("EPSG:2263",this.projection,coordinates);return coordinates},geoclient:function(response){var me=this,results=response.results;if(response.status=="OK")if(results.length==1){var result=results[0];if(result.status=="EXACT_MATCH"||result.status=="POSSIBLE_MATCH"){var location=me.parse(result);if(location.coordinates[0])me.trigger(nyc.Locate.LocateEventType.GEOCODE,location);else me.trigger(nyc.Locate.LocateEventType.AMBIGUOUS,
{input:response.input,possible:[]})}}else me.trigger(nyc.Locate.LocateEventType.AMBIGUOUS,{input:response.input,possible:me.possible(results)});else me.trigger(nyc.Locate.LocateEventType.AMBIGUOUS,{input:response.input,possible:[]})},possible:function(results){var me=this,possible=[];$.each(results,function(i,r){if(r.status="POSSIBLE_MATCH"){var location=me.parse(r);if(location.coordinates[0])possible.push(location)}});return possible},parse:function(result){var typ=result.request.split(" ")[0],r=
result.response,ln1,p,a;if(typ=="intersection"){ln1=r.streetName1+" and "+r.streetName2;p=[r.xCoordinate*1,r.yCoordinate*1];a=nyc.Geocoder.Accuracy.MEDIUM}else if(typ=="blockface"){ln1=r.firstStreetNameNormalized+" btwn "+r.secondStreetNameNormalized+" & "+r.thirdStreetNameNormalized;p=[(r.fromXCoordinate*1+r.toXCoordinate*1)/2,(r.fromYCoordinate*1+r.toYCoordinate*1)/2];a=nyc.Geocoder.Accuracy.LOW}else{var x=r.internalLabelXCoordinate,y=r.internalLabelYCoordinate;ln1=(r.houseNumber?r.houseNumber+
" ":"")+r.firstStreetNameNormalized;p=[(x&&y?x:r.xCoordinate)*1,(x&&y?y:r.yCoordinate)*1];a=x&&y?nyc.Geocoder.Accuracy.HIGH:nyc.Geocoder.Accuracy.MEDIUM}return{type:nyc.Locate.LocateResultType.GEOCODE,coordinates:this.project(p),accuracy:a,name:this.capitalize(ln1.replace(/  /," ").replace(/  /," ")+", "+r.firstBoroughName)+", NY "+(r.zipCode||r.leftSegmentZipCode||"")}},capitalize:function(s){var words=s.split(" "),result="";$.each(words,function(i,w){var word=w.toLowerCase();result+=word.substr(0,
1).toUpperCase();result+=word.substr(1).toLowerCase();result+=" "});return result.trim()}};
nyc.Geoclient.prototype.search=function(input){var me=this;input=input.trim();if(input.length==5&&!isNaN(input)){var p=me.project(nyc.Geoclient.ZIP_CODE_POINTS[input]);me.trigger(p?nyc.Locate.LocateEventType.GEOCODE:nyc.Locate.LocateEventType.AMBIGUOUS,p?{coordinates:p,accuracy:nyc.Geocoder.Accuracy.ZIP_CODE,type:nyc.Locate.LocateResultType.GEOCODE,zip:true,name:input}:{input:input,possible:[]})}else if(input.length){input=input.replace(/"/g,"").replace(/'/g,"").replace(/&/g," and ");$.ajax({url:me.url+
input,dataType:"jsonp",success:function(response){me.geoclient(response)},error:function(){console.error("Geoclient error");me.trigger(nyc.Locate.LocateEventType.ERROR)}})}};nyc.inherits(nyc.Geoclient,nyc.EventHandling);
nyc.Geoclient.ZIP_CODE_POINTS={10474:[1018466,233787],10455:[1007889,236616],10037:[1001661,235627],10024:[991450,225457],10454:[1007449,232863],10026:[997179,231835],10035:[1001886,231364],10025:[993331,230012],10035:[1006595,228454],11101:[1001319,211034],11364:[1051553,211923],10018:[984278,215509],10020:[990012,215729],11005:[1064789,214295],10017:[991869,213252],10001:[983613,213360],10011:[982781,210664],10016:[990291,210665],11104:[1006224,210564],11109:[996054,210740],10010:[988989,208515],
11367:[1032392,205392],10014:[982449,206620],10003:[987465,205563],11222:[998773,204620],11379:[1017432,200740],11429:[1056859,198057],11435:[1036960,195018],11415:[1031798,197376],11418:[1031001,193330],11433:[1043368,193721],11451:[1039899,194697],11221:[1004438,191873],11421:[1023878,191241],11372:[1016528,213126],11004:[1065606,210363],11040:[1065956,213534],10002:[988242,200171],10314:[939259,155728],11693:[1028661,168843],11228:[980891,164066],11096:[1048547,164406],11693:[1032834,164479],11209:[976172,
165379],10304:[962458,165679],10456:[1007883,242372],10472:[1021444,241624],10031:[998088,239814],10039:[1001519,240436],10459:[1013835,240084],10451:[1005368,238290],10473:[1022475,237217],10030:[1000193,237302],10027:[999088,234131],10464:[1047712,250241],10464:[1043291,247861],10461:[1028296,247902],10457:[1012388,247405],10460:[1015132,243510],10032:[1000382,244917],10452:[1005446,244483],11414:[1027256,178677],11231:[979340,182720],11232:[983612,177801],10034:[1005713,255122],10033:[1001707,
248780],10462:[1020685,249420],10040:[1003863,251914],10453:[1008152,249805],11102:[1004636,220364],11370:[1014445,217532],10021:[997020,219120],11361:[1047797,217779],11358:[1040709,216377],11362:[1057749,215220],10044:[996385,214347],11369:[1019957,217722],11103:[1008295,217197],11106:[1001397,217519],11368:[1024870,212082],11377:[1010574,210678],10036:[985413,216821],11355:[1033762,213010],10302:[945946,169124],10465:[1031495,239091],11691:[1053783,158810],11096:[1054217,162199],11223:[991665,
156781],11693:[1030676,160394],11208:[1019700,184749],11207:[1013544,183721],10004:[978925,190480],10004:[971715,190592],11413:[1053380,183328],11217:[989547,187967],11238:[994291,186584],11231:[983057,186217],11422:[1057272,180607],11420:[1036899,184708],11417:[1027410,185709],11215:[989882,181773],11357:[1036533,225804],10029:[999950,227538],"00083":[991590,220538],11356:[1028115,225277],11359:[1046026,228012],10303:[933820,171004],11234:[1004323,163783],11360:[1044984,223892],11105:[1011836,221755],
10128:[997765,224257],11371:[1022003,220457],10023:[988765,222068],11363:[1055047,220385],10028:[995910,222872],11354:[1032198,219054],11216:[998312,187241],11416:[1025796,188584],11233:[1006523,186300],11436:[1040697,185554],11213:[1000284,183308],11212:[1008387,180764],11225:[997345,180829],11218:[990799,173649],11226:[995711,174598],11219:[985166,169604],11210:[999101,167896],11230:[993494,166072],11419:[1033365,190202],11434:[1046577,185969],11204:[987887,164576],10471:[1012587,266570],10470:[1024748,
268409],10466:[1024313,263999],10467:[1019786,258782],11430:[1043607,175068],11203:[1002509,175950],10469:[1026678,255623],10468:[1013897,258046],10463:[1008780,258696],10458:[1015534,253712],11378:[1009641,202115],10009:[990043,203961],10012:[984832,203596],10013:[982892,201665],10007:[982504,199552],11237:[1004600,197083],11385:[1011367,195195],10038:[983418,197803],11206:[1000221,195003],10006:[980563,197293],11412:[1050773,193231],10005:[981339,197038],11251:[993428,194599],10004:[980174,195435],
11411:[1057763,192413],11201:[986968,192156],10004:[972576,193652],11205:[995897,192159],10305:[963310,156060],11229:[999717,158278],11214:[984E3,159330],10306:[950937,145144],11694:[1025530,149310],11224:[984306,149092],10308:[942704,140020],10282:[979981,200244],11211:[999857,199848],11249:[993704,198278],11370:[1016758,227518],10065:[994666,217698],10075:[995301,221633],10069:[987047,221849],10281:[980036,198787],11373:[1017948,208465],10279:[981949,198823],10165:[990124,213288],10168:[990733,
212960],10105:[990067,217259],10118:[988212,211939],10176:[990123,214490],10162:[997739,219667],10170:[990955,213470],10112:[989735,215947],10122:[986550,213178],10107:[989098,218425],10103:[990705,216275],10174:[991094,213106],10166:[990733,213798],10169:[990872,214089],10167:[991259,214199],10177:[990927,214381],10172:[991398,214417],10171:[991426,214709],10270:[982060,196710],10104:[990123,216312],10271:[981339,197293],10110:[989486,213943],10175:[989847,214016],10151:[991702,217332],10173:[990040,
213907],10178:[990429,212814],10119:[986217,213068],10121:[986439,212486],10123:[986827,213032],10106:[989624,218024],10158:[991177,212122],10041:[981727,195435],10120:[987242,212449],10278:[983113,199880],10155:[993143,216531],10043:[982337,195836],10081:[981838,197074],10096:[989071,214235],10097:[988461,216931],10196:[989237,215E3],10196:[989458,214963],10275:[980368,196382],10265:[982060,196164],10045:[981866,197329],10047:[988047,208660],10047:[988047,208660],10080:[980785,198167],10203:[981062,
196965],10259:[981478,197439],10260:[981921,196564],10285:[980147,199224],10286:[981727,196637],10463:[1007644,260043],10475:[1030489,258509],10464:[1036131,258338],10309:[923594,132955],10307:[916899,124411],10280:[979509,197257],10048:[980812,198532],10055:[991564,215802],10019:[989652,217477],10111:[990483,215838],10153:[991896,217478],10154:[991896,215328],10152:[991979,215584],10115:[994299,234675],10022:[993087,215620],11235:[1000973,149936],11693:[1036606,153266],11692:[1041045,155461],11697:[1009230,
143240],10312:[935583,136827],11239:[1021573,175899],11236:[1011642,172461],11220:[979421,172519],10301:[961077,172967],10310:[950582,169591],11426:[1060737,207724],11365:[1041364,208618],11001:[1065508,206646],11375:[1026883,201848],11427:[1053373,205042],11374:[1022389,203771],11366:[1039491,203659],11423:[1048812,200621],11428:[1055655,202207],11432:[1041634,200093]};window.nyc=window.nyc||{};nyc.Locate=function(){};nyc.Locate.prototype.locate=function(){};nyc.Locate.prototype.track=function(track){};nyc.Locate.prototype.search=function(input){};nyc.Locate.LocateEventType={GEOCODE:"geocode",GEOLOCATION:"geolocation",AMBIGUOUS:"ambiguous",ERROR:"error"};nyc.Locate.LocateResultType={GEOCODE:"geocode",GEOLOCATION:"geolocation"};nyc.Locate.LocateResult;nyc.Locate.LocateAmbiguous;window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};
nyc.ol.Locate=function(geocoder,projection,extentLimit){var me=this;me.projection=projection;me.extentLimit=extentLimit;geocoder.on(nyc.Locate.LocateEventType.GEOCODE,function(data){me.proxyEvent(nyc.Locate.LocateEventType.GEOCODE,data)});geocoder.on(nyc.Locate.LocateEventType.AMBIGUOUS,function(data){me.proxyEvent(nyc.Locate.LocateEventType.AMBIGUOUS,data)});geocoder.on(nyc.Locate.LocateEventType.ERROR,function(data){me.proxyEvent(nyc.Locate.LocateEventType.ERROR,data)});me.geocoder=geocoder;me.geolocation=
new ol.Geolocation({trackingOptions:{maximumAge:1E4,enableHighAccuracy:true,timeout:6E5}});me.geolocation.on("change",function(){var p=me.geolocation.getPosition(),name=ol.coordinate.toStringHDMS(p);p=me.project(p);if(me.locating){me.track(false);me.locating=false}if(me.withinLimit(p))me.trigger(nyc.Locate.LocateEventType.GEOLOCATION,{coordinates:p,heading:me.geolocation.getHeading(),accuracy:me.geolocation.getAccuracy()/me.metersPerUnit(),type:nyc.Locate.LocateResultType.GEOLOCATION,name:name})});
me.geolocation.on("error",function(error){console.error(error.message,error)})};
nyc.ol.Locate.prototype={locating:false,projection:null,extentLimit:null,proxyEvent:function(evt,data){this.trigger(evt,data)},metersPerUnit:function(){if(this.projection)return ol.proj.get(this.projection).getMetersPerUnit()||1;return 1},project:function(coordinates){if(this.projection)return proj4("EPSG:4326",ol.proj.get(this.projection).getCode(),coordinates);return coordinates},withinLimit:function(coordinates){return this.extentLimit?ol.extent.containsCoordinate(this.extentLimit,coordinates):
true}};nyc.ol.Locate.prototype.locate=function(){this.locating=true;this.geolocation.setTracking(true)};nyc.ol.Locate.prototype.track=function(track){this.geolocation.setTracking(track)};nyc.ol.Locate.prototype.search=function(input){this.geocoder.search(input)};nyc.inherits(nyc.ol.Locate,nyc.EventHandling);window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};
nyc.ol.Popup=function(map,options){var me=this;options=options||{};this.options=options;me.container=$(document.createElement("div"));me.container.addClass("popup");me.closer=$(document.createElement("a"));me.closer.addClass("popup-closer");me.container.append(me.closer);me.closer.click(function(){me.container.fadeOut()});me.content=$(document.createElement("div"));me.content.addClass("popup-content");me.container.append(me.content);options.element=me.container[0];options.stopEvent=true;ol.Overlay.call(this,
options);map.addOverlay(me);if(me.options.coordinates)me.show(me.options)};ol.inherits(nyc.ol.Popup,ol.Overlay);nyc.ol.Popup.prototype.show=function(options){this.setOptions(options);this.setPosition(this.coordinates);if(!this.visible())this.container.fadeIn();this.pan()};nyc.ol.Popup.prototype.visible=function(){return this.container.css("display")=="block"};nyc.ol.Popup.prototype.isMobile=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod|iOS|Android)/g)!=null};
nyc.ol.Popup.prototype.setOptions=function(options){if(options)for(var o in options)this.options[o]=options[o];this.coordinates=this.options.coordinates;this.content.html(this.options.html||"").trigger("create");if(this.isMobile())this.content.find("a, button").each(function(_,n){if($(n).attr("onclick"))$(n).bind("tap",function(){$(n).trigger("click")})});this.margin=this.options.margin||[10,10,10,10]};nyc.ol.Popup.prototype.hide=function(){this.container.fadeOut()};
nyc.ol.Popup.prototype.pan=function(coord){var n=this.getElement(),map=this.getMap(),view=map.getView(),tailHeight=parseInt($(n).css("bottom")),tailOffsetLeft=-parseInt($(n).css("left")),popOffset=this.getOffset(),popPx=map.getPixelFromCoordinate(this.options.coordinates),mapSize=map.getSize(),popSize={width:$(n).width(),height:$(n).height()+tailHeight},tailOffsetRight=popSize.width-tailOffsetLeft,fromLeft=popPx[0]-tailOffsetLeft-this.margin[3],fromRight=mapSize[0]-(popPx[0]+tailOffsetRight)-this.margin[1],
fromTop=popPx[1]-popSize.height+popOffset[1]-this.margin[0],fromBottom=mapSize[1]-(popPx[1]+tailHeight)-popOffset[1]-this.margin[2],center=view.getCenter(),px=map.getPixelFromCoordinate(center);if(fromRight<0)px[0]-=fromRight;else if(fromLeft<0)px[0]+=fromLeft;if(fromTop<0)px[1]+=fromTop;else if(fromBottom<0)px[1]-=fromBottom;map.beforeRender(ol.animation.pan({source:center}));view.setCenter(map.getCoordinateFromPixel(px))};window.nyc=window.nyc||{};nyc.ol=nyc.ol||{};nyc.ol.FeatureLabel;nyc.ol.FeatureLabelFunction;nyc.ol.FeatureTipDef;
nyc.ol.FeatureTip=function(map,tipDefs){this.map=map;this.mapDiv=map.getTarget();if(tipDefs)this.addtipDefs(tipDefs);if(!$(this.mapDiv).children(".feature-tip").length)$(this.mapDiv).append('<div class="feature-tip" role="tooltip"></div><div class="feature-tip-helper" style="left:-1000px;top:-1000px"></div>');this.tip=$(this.mapDiv).children(".feature-tip");this.helper=$(this.mapDiv).children(".feature-tip-helper");$(map.getViewport()).mousemove($.proxy(this.label,this))};
nyc.ol.FeatureTip.prototype={map:null,mapDiv:null,tip:null,helper:null,hide:function(){this.tip.fadeOut()},label:function(e){var px=this.map.getEventPixel(e.originalEvent),lbl=this.map.forEachFeatureAtPixel(px,function(f,_){return f&&f.getLabel?f.getLabel():null});if(lbl){this.tip.html(lbl.text).css({left:px[0]+10+"px",top:px[1]+10+"px"}).show();this.tip[0].className="feature-tip "+(lbl.cssClass||"");this.flip(lbl,px)}else this.tip.fadeOut()},flip:function(lbl,px){var width=this.helper.html(lbl.text).width(),
height=this.helper.height();this.helper[0].className="feature-tip-helper "+(lbl.cssClass||"");if(this.tip.position().left+width>$(this.mapDiv).width())this.tip.css("left",px[0]-width-10+"px");if(this.tip.position().top+height>$(this.mapDiv).height())this.tip.css("top",px[1]-height-10+"px")}};
nyc.ol.FeatureTip.prototype.addtipDefs=function(tipDefs){$.each(tipDefs,function(_,def){var src=def.source,func=def.labelFunction,features=src.getFeatures();if(features.getArray)features=features.getArray();$.each(features,function(_,f){f.getLabel=func});src.on("addfeature",function(e){e.feature.getLabel=func})})};window.nyc=window.nyc||{};
nyc.Lang=function(){var langClass=function(target,languages){var codes=[],div=$(nyc.Lang.HTML);nyc.lang=this;this.hints=[];this.namedCodes={};$(target).append(div);for(var code in languages){var name=languages[code].val,opt=$("<option></option>").attr("value",name).html(languages[code].desc);$("#lang-choice").append(opt);codes.push(code);this.hints.push(languages[code].hint);this.namedCodes[name]=code}this.codes=codes.toString();this.languages=languages;div.trigger("create");$.getScript("//translate.google.com/translate_a/element.js?cb=nyc.lang.init")};
langClass.prototype={namedCodes:null,code:"",codes:"",translate:null,hints:null,languages:null,init:function(){nyc.lang.translate=new google.translate.TranslateElement({pageLanguage:"en",includedLanguages:nyc.lang.codes,layout:google.translate.TranslateElement.InlineLayout.SIMPLE,autoDisplay:false},"lang-trans");$("#lang-choice").show();nyc.lang.initDropdown();nyc.lang.setLangDropdown();$("#lang-choice-button span").html("Translate").show();nyc.lang.hack();nyc.lang.trigger(nyc.Lang.EventType.READY)},
showHint:function(){var hints=this.hints,h=0;setInterval(function(){$("#lang-choice-button span").html(hints[h]||"Translate");h++;if(h==hints.length)h=0},1E3)},chooseLang:function(lang){var choices=$("iframe.goog-te-menu-frame:first").contents().find(".goog-te-menu2-item span.text");if(choices.length){if(lang=="English")nyc.lang.showOriginalText();else $(choices).each(function(){if($(this).text()==lang){$(this).click();return false}});$("#lang-choice-button span").show();this.code=nyc.lang.namedCodes[lang]||
"en";this.trigger(nyc.Lang.EventType.CHANGE,this.code)}else{var me=this;setTimeout(function(){me.chooseLang(lang)},100)}},initDropdown:function(){var me=this;$("#lang-choice").change(function(){me.chooseLang($(this).val())})},showOriginalText:function(){var googBar=$("iframe.goog-te-banner-frame:first");$(googBar.contents().find(".goog-te-button button")).each(function(){if($(this).text()=="Show original"){$(this).trigger("click");if($("#lang-choice").val()!="English")$("#lang-choice").val("English");
return false}})},defaultLang:function(){return navigator.language?navigator.language.split("-")[0]:"en"},setLangDropdown:function(){var defLang=this.defaultLang(),langCode=this.getCookieValue();this.showHint();if(!langCode){for(var code in this.languages)if(code.indexOf(defLang)==0){langCode=code;break}langCode=langCode||"en"}$("#lang-choice").val(this.languages[langCode].val).trigger("change")},lang:function(){return this.code},hack:function(){$("input[placeholder]").each(function(){var next=$(this).next();
if(!next.hasClass("lang-placeholder"))$(this).after('<span class="lang-placeholder">'+$(this).attr("placeholder")+"</span>");else $(this).attr("placeholder",next.html().replace(/<font>/g,"").replace(/<\/font>/g,""))});$("font").each(function(){if($(this).data("lang-hack")!="hacked"){var parent=$(this).parent();$(this).data("lang-hack","hacked");if(parent.length&&parent[0].tagName.toUpperCase()!="FONT"&&parent.data("role")=="button")$(this).click(function(event){event.stopImmediatePropagation();parent.trigger("click")})}});
$("body").css("top","auto");$("#goog-gt-tt").remove();setTimeout($.proxy(this.hack,this),200)},getCookie:function(){var cookies=document.cookie.split(";");for(var i=0;i<cookies.length;i++){var cookie=cookies[i];while(cookie.charAt(0)==" ")cookie=cookie.substring(1,cookie.length);if(cookie.indexOf("googtrans=")==0)return cookie.substring(10,cookie.length)}},getCookieValue:function(){var cookie=this.getCookie();if(cookie){cookie=cookie.split("/");cookie=cookie[2];return cookie}}};return langClass}();
nyc.inherits(nyc.Lang,nyc.EventHandling);nyc.Lang.EventType={READY:"ready",CHANGE:"change"};nyc.Lang.HTML="<div id='lang-btn' title='Translate...'>"+"<div id='lang-trans'></div>"+"<select id='lang-choice' class='notranslate' translate='no'></select>"+"</div>";nyc.Share=function(target,feedbackUrl){var me=this,html=nyc.Share.HTML,title=$('meta[property="og:title"]').attr("content");html=html.replace(/\${url}/g,$('meta[property="og:url"]').attr("content"));html=html.replace(/\${title}/g,title);html=html.replace(/\${feedbackUrl}/,feedbackUrl);html=html.replace(/\${description}/g,$('meta[property="og:description"]').attr("content"));$(target).append(html).trigger("create");if(!feedbackUrl)$("#feedback-btn").remove();$("*").click(function(e){if($("#share-btns").css("opacity")==
1)$("#share-btns").fadeOut()});if(this.isIosAppMode())$("#email-btn").attr("target","_blank")};nyc.Share.prototype.isIosAppMode=function(){return navigator.standalone&&navigator.userAgent.match(/(iPad|iPhone|iPod|iOS)/g)};
nyc.Share.HTML='<a id="share-btn" class="ctl ctl-btn" data-role="button" title="Share..." onclick="$(\'#share-btns\').fadeToggle();">'+'<span class="noshow">Share...</span>'+"</a>"+'<div id="share-btns" class="ctl">'+'<a id="feedback-btn" class="ctl-btn" data-role="button" href="${feedbackUrl}" target="_blank" title="Feedback">'+'<span class="noshow">Feedback</span>'+"</a>"+'<a id="facebook-btn" class="ctl-btn" data-role="button" href="https://www.facebook.com/sharer/sharer.php?u=${url}" target="_blank" title="Facebook">'+
'<span class="noshow">Facebook</span>'+"</a>"+'<a id="twitter-btn" class="ctl-btn" data-role="button" href="https://twitter.com/intent/tweet?text=${url} @nycgov&source=webclient" target="_blank" title="Twitter">'+'<span class="noshow">Twitter</span>'+"</a>"+'<a id="google-btn" class="ctl-btn" data-role="button" href="https://plus.google.com/share?url=${url}" target="_blank" title="Google+">'+'<span class="noshow">Google+</span>'+"</a>"+'<a id="linkedin-btn" class="ctl-btn" data-role="button" href="http://www.linkedin.com/shareArticle?mini=true&url=${url}" target="_blank" title="LinkedIn">'+
'<span class="noshow">LinkedIn</span>'+"</a>"+'<a id="tumblr-btn" class="ctl-btn" data-role="button" href="http://www.tumblr.com/share/link?url=${url}&name=${title}&description=via%20NYC.gov" target="_blank" title="Tumblr">'+'<span class="noshow">Tumblr</span>'+"</a>"+'<a id="email-btn" class="ctl-btn" data-role="button" href="mailto:?subject=${title}&body=${description}%0A%0A${url}" title="email">'+'<span class="noshow">Email</span>'+"</a>"+"</div>";window.nyc=window.nyc||{};
nyc.Style=function(){var styleClass=function(){this.facilityCache={};this.locationCache=null};styleClass.prototype={facilityCache:null,locationCache:null,isIe:function(){return"ActiveXObject"in window},imgExt:function(){return this.isIe()?".png":".svg"},zoom:function(resolution){var resolutions=nyc.ol.layer.BaseLayer.RESOLUTIONS,zoom=resolutions.indexOf(resolution);if(zoom==-1)for(var z=0;z<resolutions.length;z++)if(resolution>resolutions[z]){zoom=z;break}return zoom>-1?zoom:resolutions.length-1},
locationStyle:function(feature,resolution){if(!this.locationCache){var image="img/me0"+this.imgExt();this.locationCache=[new ol.style.Style({image:new ol.style.Icon({scale:48/512,src:image,offset:navigator.userAgent.match(/Safari/g)?undefined:[0,24]})})]}return this.locationCache},facilityStyle:function(feature,resolution){var zoom=this.zoom(resolution),radius=[8,8,8,12,12,12,16,16,16,16,16][zoom];if(!this.facilityCache[zoom])this.facilityCache[zoom]=[new ol.style.Style({image:new ol.style.Circle({radius:radius,
fill:new ol.style.Fill({color:"#181f4a"}),stroke:new ol.style.Stroke({color:"white",width:radius<12?1.5:2})})})];return this.facilityCache[zoom]}};return styleClass}();window.nyc=window.nyc||{};
nyc.App=function(){var appClass=function(map,csvUrl,featureDecorations,content,style,controls,locate,directions,popup,pager,lang){var me=this;me.map=map;me.content=content;me.view=map.getView();me.controls=controls;me.locate=locate;me.directions=directions;me.popup=popup;me.pager=pager;me.location={};me.zoneOrders={};me.tips=[];lang.on(nyc.Lang.EventType.CHANGE,function(code){var word=content.message("lifenet_word_"+nyc.lang.lang())||content.message("lifenet_word"),number=content.message("lifenet_number_"+
nyc.lang.lang())||content.message("lifenet_number");$(".lifenet-number").html(number);$(".lifenet-word").html(word);$("a.lifenet-word").attr("href","tel:"+word)});$("#copyright").html(content.message("copyright",{yr:(new Date).getFullYear()}));me.facilitySource=new nyc.ol.source.FilteringAndSorting({},[content,featureDecorations.fieldAccessors,featureDecorations.htmlRenderer]);me.facilityLayer=new ol.layer.Vector({map:map,source:me.facilitySource,style:$.proxy(style.facilityStyle,style)});me.tips.push(new nyc.ol.FeatureTip(map,
[{source:me.facilitySource,labelFunction:me.facilityTip}]));me.loadCsv(csvUrl);me.locationSource=new nyc.ol.source.Decorating({},[{getName:function(){return this.get("name")}}]);new ol.layer.Vector({map:map,source:me.locationSource,style:$.proxy(style.locationStyle,style)});me.tips.push(new nyc.ol.FeatureTip(map,[{source:me.locationSource,labelFunction:me.locationTip}]));$("#panel, .banner, .ctl").hover($.proxy(me.hideTips,me));$("#filters select").change($.proxy(me.filter,me));controls.on(nyc.ol.control.ZoomSearch.EventType.GEOLOCATE,
$.proxy(locate.locate,locate));controls.on(nyc.ol.control.ZoomSearch.EventType.DISAMBIGUATED,$.proxy(me.zoomLocation,me));controls.on(nyc.ol.control.ZoomSearch.EventType.SEARCH,$.proxy(locate.search,locate));locate.on(nyc.Locate.LocateEventType.GEOCODE,$.proxy(me.zoomLocation,me));locate.on(nyc.Locate.LocateEventType.GEOLOCATION,$.proxy(me.zoomLocation,me));locate.on(nyc.Locate.LocateEventType.AMBIGUOUS,$.proxy(me.ambiguous,me));locate.on(nyc.Locate.LocateEventType.ERROR,function(){controls.searching(false)});
directions.on(nyc.Directions.EventType.CHANGED,$.proxy(me.resize,me));$(window).resize($.proxy(me.resize,me));$("body").pagecontainer({change:function(){$(window).trigger("resize")}});map.on("click",$.proxy(me.mapClick,me));$("#transparency").change($.proxy(me.transparency,me));$("#map-tab-btn a").click($.proxy(me.mapSize,me));if(me.isMobile())$("a, button").each(function(_,n){if($(n).attr("onclick"))$(n).bind("tap",function(){$(n).trigger("click")})});$("input").focus(function(){me.skipResize=true;
setTimeout(function(){me.skipResize=false},1E3)})};appClass.prototype={map:null,view:null,zoneSource:null,zoneLayer:null,facilitySource:null,facilityLayer:null,locationSource:null,content:null,controls:null,locate:null,directions:null,popup:null,tips:null,location:null,zoneOrders:null,skipResize:false,vcard:function(node){var me=this,target=$(node),ios=target.data("ios"),id=target.data("feature-id"),last=target.data("last-click"),feature=this.facilitySource.getFeatureById(id),now=(new Date).getTime();
if(last*1+600<now||!last){$.ajaxSettings.traditional=true;if(ios){var text=$("#vcard-download").html();text=text.replace(/<font>/gi,"");text=text.replace(/<\/font>/gi,"");window.open("vcard.html?"+$.param(feature.vCardData())+"&text="+text)}else window.open("/vcard/?"+$.param(feature.vCardData()));target.data("last-click",now)}},loadCsv:function(csvUrl){var me=this;$.support.cors=true;$.ajax({url:csvUrl+"&today="+encodeURIComponent((new Date).toLocaleDateString()),dataType:"text",success:function(csvData){var csvFeatures=
$.csv.toObjects(csvData),wkt=new ol.format.WKT,features=[];$.each(csvFeatures,function(id,f){var lngLat=proj4("EPSG:4326","EPSG:2263",[f.longitude,f.latitude]),feature=wkt.readFeature("POINT ("+lngLat[0]+" "+lngLat[1]+")");feature.setProperties(f);feature.setId(id);features.push(feature)});me.facilitySource.addFeatures(features);me.initList();me.clearFirstLoad()},error:function(){me.alert(me.content.message("data_load_error"))}})},initList:function(){if(!$("#facilities div").length)this.list(this.location.coordinates)},
details:function(node){var me=this,target=$(node),last=target.data("last-click"),now=(new Date).getTime();if(last*1+400<now||!last){var parent=target.parent().parent();parent.parent().find("ul").slideToggle(function(){if(parent.parent().hasClass("inf-pop"))me.popup.pan()});target.data("last-click",now)}},clearFirstLoad:function(){if($("#lang-choice-button").length)$("#first-load").fadeOut();else setTimout(this.ready,200)},resize:function(event){if(!this.skipResize){var h=$("#dir-toggle").css("display")==
"block"?$("#dir-toggle").height():0;$("#directions").height($("#dir-panel").height()-h-$(".banner").height()-$(".footer").height()-$("#dir-content").height()-$("#copyright").height()-15);if(event&&$("#splash").css("display")=="none")this.layout();this.map.render()}},layout:function(event){var mobile=$("#panel").width()==$(window).width();$("#copyright").css("color","#181f4a");$("#tabs").tabs({activate:function(event,ui){$("#map-page .ui-content").css("z-index",mobile&&ui.newPanel.attr("id")=="map-tab"?
"1000":"auto")}});$("#tabs li a").removeClass("ui-btn-active");$("#map-tab-btn")[mobile?"show":"hide"]();$("#tabs").tabs("refresh");$("#tabs").tabs({active:1});$("#facility-tab-btn a").addClass("ui-btn-active");this.map.updateSize();setTimeout(function(){$("#filter-tab").append($("#filters"));$("#click-blocker").fadeOut()},400)},zoomFacility:function(id){var me=this,feature=me.facilitySource.getFeatureById(id);if($("#panel").width()==$(window).width()){$("#tabs").tabs({active:0});$("#tabs li a").removeClass("ui-btn-active");
$("#map-tab-btn a").addClass("ui-btn-active")}me.zoomCoords(feature.getCoordinates());me.map.once("moveend",function(){me.showPopup(feature.getCoordinates(),feature.html("inf-pop"))})},facilityInView:function(){var extent=this.view.calculateExtent(this.map.getSize()),closest=this.facilitySource.getClosestFeatureToCoordinate(this.location.coordinates);if(!ol.extent.containsCoordinate(extent,closest.getCoordinates())){extent=ol.extent.extend(extent,closest.getGeometry().getExtent());this.map.beforeRender(ol.animation.zoom({resolution:this.view.getResolution()}),
ol.animation.pan({source:this.view.getCenter()}));this.view.fit(extent,this.map.getSize())}},zoomLocation:function(data){this.controls.val(data.type==nyc.Locate.LocateEventType.GEOLOCATION?"":data.name);this.list(data.coordinates);this.location=data;this.locationSource.clear();this.locationSource.addFeature(new ol.Feature({geometry:new ol.geom.Point(data.coordinates),name:data.name}));this.zoomCoords(data.coordinates,$.proxy(this.facilityInView,this));this.facilityInView()},ambiguous:function(data){if(data.possible.length)this.controls.disambiguate(data.possible);
else{this.controls.searching(false);this.alert(this.content.message("bad_input"))}},direct:function(id){var me=this,feature=me.facilitySource.getFeatureById(id),to=feature.getAddress(),name=feature.getName(),from=me.location.name||"";$("body").pagecontainer("change",$("#dir-page"),{transition:"slideup"});if(me.lastDir!=from+"|"+to){var args={from:unescape(from),to:unescape(to),facility:unescape(name)};me.lastDir=from+"|"+to;me.directions.directions(args)}},mapSize:function(){var map=this.map;setTimeout(function(){map.updateSize()},
10)},list:function(coordinates){var container=$("#facilities");container.empty();this.pager.reset(this.facilitySource.sort(coordinates));this.next()},next:function(){var facilities=this.pager.next();this.appendInfo($("#facilities"),facilities);$("div.list-more")[facilities.length<10?"hide":"show"]()},isMobile:function(){return navigator.userAgent.match(/(iPad|iPhone|iPod|iOS|Android)/g)},appendInfo:function(container,facilities){$.each(facilities,function(i,facility){var info=$(facility.html("inf-list"));
if(i%2!=0)info.addClass("odd-row");container.append(info).trigger("create")});if(this.isMobile())container.find("a, button").each(function(_,n){if($(n).attr("onclick"))$(n).bind("tap",function(){$(n).trigger("click")})})},qstr:function(qstr){var args={};try{var params=qstr.substr(1).split("&");for(var i=0;i<params.length;i++){var p=params[i].split("=");args[p[0]]=decodeURIComponent(p[1])}}catch(ignore){}if(args.address)this.locate.search(args.address);else this.locate.locate()},filter:function(){var filters=
[];$("#filters select").each(function(_,select){var props=$(select).val().split(",");$.each(props,function(_,prop){if(prop!="any")filters.push({property:prop,values:["1"]})})});this.facilitySource.filter(filters);this.list(this.location.coordinates);if(!this.facilitySource.getFeatures().length){this.alert(this.content.message("data_filter_warn"));$("div.list-more").hide()}},zoomCoords:function(coords,afterZoom){if(afterZoom)this.map.once("moveend",afterZoom);this.map.beforeRender(ol.animation.zoom({resolution:this.view.getResolution()}),
ol.animation.pan({source:this.view.getCenter()}));this.view.setZoom(7);this.view.setCenter(coords)},mapClick:function(evt){var me=this,map=me.map,px=evt.pixel;map.forEachFeatureAtPixel(px,function(feature,layer){if(layer==me.facilityLayer){var coords=feature.getCoordinates();if(coords){me.showPopup(coords,feature.html("inf-pop"));return true}}})},showPopup:function(coordinates,html){this.hideTips();this.popup.setOffset([0,-10]);this.popup.show({coordinates:coordinates,html:html})},facilityTip:function(){return{cssClass:"tip-facility",
text:this.message("facility_tip",{name:this.getName()})}},locationTip:function(){return{cssClass:"tip-location",text:this.getName().replace(/,/,"<br>")}},hideTips:function(){$.each(this.tips,function(_,tip){tip.hide()})},alert:function(msg){$("body").append($("#alert"));$("#alert-msg").html(msg);$("#alert").fadeIn();$("#alert button").focus()}};return appClass}();//# sourceMappingURL=nyc-min.js.map
