/*

nyc-crime-v0.1.1

*/
var nyc=nyc||{};
nyc.App=function(options){var me=this;me.map=options.map;me.viewSwitcher=options.viewSwitcher;me.mapType=options.mapType;me.crimeType=options.crimeType;me.dateRange=options.dateRange;me.allChart=options.allChart;me.summaryChart=options.summaryChart;me.locationInfo=options.locationInfo;me.crimeDrillDown=options.crimeDrillDown;me.boroughNames=options.boroughNames||me.boroughNames;me.viewSwitcher.on("updated",me.updateLegend,me);me.mapType.on("change",function(){$("#legend").empty()});me.mapType.on("change",
me.updateView,me);me.crimeType.on("change",me.updateView,me);me.dateRange.on("change",me.updateView,me);options.locationMgr.on(nyc.Locate.EventType.GEOCODE,me.currentPrecinct,me);options.locationMgr.on(nyc.Locate.EventType.GEOLOCATION,me.currentPrecinct,me);me.popups();$("#btn-toggle").click(me.toggle);$("#chart-pane").collapsible({expand:function(){me.updateSummaryChart()}});$(window).unbind("resize").bind("resize",$.proxy(me.resize,me));$(window).unbind("orientationchange").bind("orientationchange",
$.proxy(me.resize,me));$("#chart-all").css("left",$(window).width()+50+"px");me.map.on("viewreset",$.proxy(me.checkForUpdate,me));me.updateView();me.prevZoom=me.map.getZoom()};
nyc.App.prototype={map:null,viewSwitcher:null,mapType:null,crimeType:null,dateRange:null,allChart:null,summaryChart:null,locationInfo:null,crimeDrillDown:null,boroughNames:{1:"Manhattan",2:"Bronx",3:"Brooklyn",4:"Queens",5:"Staten Isl."},location:null,dialog:null,prevZoom:-1,crimeTypePlurals:{BURGLARY:"Burglaries","FELONY ASSAULT":"Felony Assaults","GRAND LARCENY":"Grand Larcenies","GRAND LARCENY OF MOTOR VEHICLE":"Grand Larcenies of Motor Vehicles",MURDER:"Murders",RAPE:"Rapes",ROBBERY:"Robberies"},
hideAllChart:function(){$("#chart-all").animate({left:$(window).width()+50});$("#chart-all-close").hide()},toggle:function(event){var btn=$(event.target);btn.toggleClass("btn-map").toggleClass("btn-panel");$("#panel").slideToggle()},drillDownLink:function(btn,popup){var data=popup.popupEventData[3];if(data.type=="Crimes"&&data.crime_count){var me=this;var list=$(popup.infowin.el).find("ul.crime-count-type");$(btn).toggleClass("ui-icon-carat-u").toggleClass("ui-icon-carat-d");if(list.children().length==
0)me.drillDown(data,popup);else list.slideToggle(function(){me.panPopup(popup)})}},drillDown:function(data,popup){var me=this,filters=me.filters().filterValues,dao;if(data.pct){filters.precinct={pct:data.pct};dao=this.crimeDrillDown.precinct}else if(data.cartodb_id){filters.sector={cartodb_id:data.cartodb_id};dao=this.crimeDrillDown.sector}else{filters.location={x:data.x,y:data.y};dao=this.crimeDrillDown.location}dao.data(filters,function(data){var list=$(popup.infowin.el).find("ul.crime-count-type");
$.each(data.rows,function(_,row){list.append('\x3cli class\x3d"crime-type-count"\x3e\x3cspan class\x3d"crime-type-indent"\x3e'+'\x3cspan class\x3d"fmt-num"\x3e'+row.crime_count+"\x3c/span\x3e "+me.crimeTypePlurals[row.type]+"\x3c/span\x3e\x3c/li\x3e")});nyc.util.formatNumberHtml({elements:".crime-type-indent .fmt-num"}).removeClass("fmt-num");list.slideToggle(function(){me.panPopup(popup)})})},panPopup:function(popup){var pop=$(popup.infowin.el),list=pop.find("ul.crime-count-type");if(list.css("display")==
"block"){var infoTop=pop.position().top;if(infoTop<0)this.map.panBy([0,infoTop-10])}},currentPrecinct:function(data){var me=this,lngLat=data.coordinates;this.location=data;data=data.data||{};me.precinct=data.pct||data.policePrecinct||data.leftSegmentPolicePrecinct;me.boro=!isNaN(data.boro)?data.boro:data.boroughCode1In;if(isNaN(me.precinct)||isNaN(me.boro))me.locationInfo.data({location:{lng:lngLat[0],lat:lngLat[1]}},function(data){if(data.rows.length){me.precinct=data.rows[0].pct;me.boro=data.rows[0].boro;
me.updateSummaryChart()}else $("#chart-sum").addClass("chart-none")});else me.updateSummaryChart()},winWidth:function(){return $(window).width()},resize:function(){if($("#chart-all").position().left>0)$("#chart-all").css("left",this.winWidth()+50+"px");if(this.winWidth()>=495)$("#panel").show();if($("#panel").css("display")=="none")$("#btn-toggle").removeClass("btn-map").addClass("btn-panel");else $("#btn-toggle").removeClass("btn-panel").addClass("btn-map");var me=this;setTimeout(function(){me.chartHeight();
me.allChart.render()},nyc.util.isIos()?1E3:0)},chartHeight:function(){if($("#chart-all").height()<320){$("#chart-all").height($("body").height()-45);$("#chart-all canvas").height($("#chart-all").height()-85)}},crimeTypesParam:function(){var crimeType=this.crimeType.val(),params={displayType:this.crimeTypePlurals[crimeType]||"Crimes"};if(crimeType=="*")params.crimeType="'BURGLARY','FELONY ASSAULT','GRAND LARCENY','GRAND LARCENY OF MOTOR VEHICLE','MURDER','RAPE','ROBBERY'";else params.crimeType="'"+
crimeType+"'";return params},filters:function(yearOffset){var crimeTypeParams=this.crimeTypesParam(),start=this.date(this.dateRange.val().start,yearOffset),end=this.date(this.dateRange.val().end,yearOffset),descriptionValues={displayType:crimeTypeParams.displayType,displayDates:start.toLocaleDateString()+" - "+end.toLocaleDateString()},filterValues={mo:{min_mo:start.getFullYear()*100+start.getMonth()+1,max_mo:end.getFullYear()*100+end.getMonth()+1},crimeType:{display_type:crimeTypeParams.displayType,
crime_types:crimeTypeParams.crimeType}};return{filterValues:filterValues,descriptionValues:descriptionValues}},appendLocationFilters:function(filterValues){if(this.location)filterValues.areas={pct:this.precinct,boro:this.boro,boro_name:this.boroughNames[this.boro]||""}},chartFilters:function(){var series0=this.filters(),start=this.dateRange.val().start,end=this.dateRange.val().end,result={filterValues:[series0.filterValues],descriptionValues:{displayType:series0.descriptionValues.displayType,seriesTitles:[series0.descriptionValues.displayDates]}};
this.appendLocationFilters(series0.filterValues);var diff=this.secondSeries(start,end);if(diff){var series1=this.filters(diff);this.appendLocationFilters(series1.filterValues);result.filterValues.push(series1.filterValues);result.descriptionValues.seriesTitles.push(series1.descriptionValues.displayDates)}return result},secondSeries:function(start,end){var result=0;if(start.getFullYear()==end.getFullYear()){var startBefore=new Date(start),endAfter=new Date(end);startBefore.setFullYear(startBefore.getFullYear()-
1);endAfter.setFullYear(endAfter.getFullYear()+1);if(startBefore>=this.dateRange.minDate)result=-1;else if(endAfter<=this.dateRange.maxDate)result=1}return result},date:function(date,yearOffset){yearOffset=yearOffset||0;date=new Date(date);date.setFullYear(date.getFullYear()+yearOffset);return date},checkForUpdate:function(){var zoom=this.map.getZoom();if(this.prevZoom<13&&zoom>=13||this.prevZoom>12&&zoom<=12)this.updateView();this.prevZoom=zoom;$("#legend")[this.map.getZoom()<14?"addClass":"removeClass"]("small")},
updateView:function(){var filters=this.filters(),view=this.mapType.val();$("#spinner").show();if(view=="location"&&this.map.getZoom()<13)view="sector";this.disableChoices();this.viewSwitcher.switchView(view,filters.filterValues,filters.descriptionValues);this.updateAllChart();this.updateSummaryChart()},disableChoices:function(){var disabled=this.crimeType.val()=="RAPE";this.mapType.disabled("location",disabled);this.mapType.disabled("heat",disabled);this.crimeType.disabled("RAPE",this.mapType.val()!=
"precinct")},updateLegend:function(legendHtml){var legend=$(legendHtml);nyc.util.formatNumberHtml({elements:legend.find(".fmt-num")}).removeClass("fmt-num");$("#spinner").hide();$("#legend").html(legend);$("#first-load").fadeOut()},updateSummaryChart:function(){if(this.location&&$("#chart-sum:visible").length){var filters=this.chartFilters();this.summaryChart.chart(filters.filterValues,$("#chart-sum .chart-title"),filters.descriptionValues);$("#chart-sum").removeClass("chart-none")}},showAllChart:function(){var chart=
$("#chart-all");this.updateAllChart();if(chart.position().left>0){chart.animate({left:0},$.proxy(this.updateAllChart,this));$("#chart-all-close").show()}},updateAllChart:function(force){if(force||$("#chart-all").position().left<$(window).width()){var filters=this.chartFilters();this.chartHeight();this.allChart.chart(filters.filterValues,$("#chart-all .chart-title"),filters.descriptionValues)}},popups:function(){var views=this.viewSwitcher.views;new nyc.carto.Popup({map:this.map,layer:views.precinct.layer,
interactivity:["pop","name","pct","type","crime_count","per1000"],template:$("#info-pct").html(),onShowPopup:$.proxy(this.setupPopup,this),onTipChange:this.tipChange});new nyc.carto.Popup({map:this.map,layer:views.sector.layer,interactivity:["cartodb_id","type","crime_count"],template:$("#info-sct").html(),onShowPopup:$.proxy(this.setupPopup,this),onTipChange:this.tipChange});new nyc.carto.Popup({map:this.map,layer:views.location.layer,interactivity:["x","y","type","crime_count"],template:$("#info-loc").html(),
onShowPopup:$.proxy(this.setupPopup,this),onTipChange:this.tipChange})},setupPopup:function(popup){var me=this,btn=$(popup.infowin.el).find(".crime-count a");nyc.util.formatNumberHtml({elements:".cartodb-popup .fmt-num"}).removeClass("fmt-num");if(!btn.data("drilldown")){btn.data("drilldown",true);btn.click(function(event){me.drillDownLink(event.target,popup)})}},tipChange:function(){nyc.util.formatNumberHtml({elements:".cartodb-tooltip .fmt-num"}).removeClass("fmt-num")}};nyc.App.Options;$(document).ready(function(){new nyc.Share("#map");var mapType=new nyc.Radio({target:"#map-type-input",title:"Map Type",choices:[{value:"precinct",label:"Precinct Map"},{value:"location",label:"Crime Location Map"},{value:"heat",label:"Heat Map"}]});var crimeType=new nyc.Radio({target:"#crime-type-input",title:"Crime Type",choices:[{value:"*",label:"All"},{value:"BURGLARY",label:"Burglary"},{value:"FELONY ASSAULT",label:"Felony Assault"},{value:"GRAND LARCENY",label:"Grand Larceny"},{value:"GRAND LARCENY OF MOTOR VEHICLE",
label:"Grand Larceny of Motor Vehicle"},{value:"MURDER",label:"Murder"},{value:"RAPE",label:"Rape"},{value:"ROBBERY",label:"Robbery"}]});var cartoSql=new cartodb.SQL({user:"nycmap"});var sectorSql="SELECT * FROM prd_crime_sector(${min_mo}, ${max_mo}, '${display_type}', ARRAY[${crime_types}])";var locationSql="SELECT * FROM prd_crime_location(${min_mo}, ${max_mo}, '${display_type}', ARRAY[${crime_types}])";var precinctSql="SELECT * FROM prd_crime_precinct(${min_mo}, ${max_mo}, '${display_type}', ARRAY[${crime_types}])";
var heatSql="SELECT * FROM stg_crime_heat(${min_mo}, ${max_mo}, ARRAY[${crime_types}])";var allChartSql="SELECT * FROM stg_crime_chart_all(${min_mo}, ${max_mo}, '${display_type}', ARRAY[${crime_types}])";var summaryChartSql="SELECT * FROM stg_crime_chart_summary(${min_mo}, ${max_mo}, '${display_type}', ARRAY[${crime_types}], ${pct}, ${boro}, '${boro_name}')";function layersLoaded(precinctLayer,sectorLayer,locationLayer,heatLayer){var precinctSym=new nyc.carto.JenksSymbolizer({cartoSql:cartoSql,jenksColumn:"per1000",
outlierFilter:"pct NOT IN (22, -99)",baseCss:"#prd_crime_precinct{polygon-opacity:0.6;line-color:#000;line-width:1.5;line-opacity:0.5;}#prd_crime_precinct[pct\x3d22]{polygon-fill:black;polygon-opacity:0.2;}#prd_crime_precinct[pct\x3d-99]{polygon-fill:black;polygon-opacity:0.2;}",cssRules:["#prd_crime_precinct[per1000\x3c\x3d${value}][pct!\x3d22][pct!\x3d-99]{polygon-fill:rgb(254,237,222);}","#prd_crime_precinct[per1000\x3c\x3d${value}][pct!\x3d22][pct!\x3d-99]{polygon-fill:rgb(253,190,133);}","#prd_crime_precinct[per1000\x3c\x3d${value}][pct!\x3d22][pct!\x3d-99]{polygon-fill:rgb(253,141,60);}",
"#prd_crime_precinct[per1000\x3c\x3d${value}][pct!\x3d22][pct!\x3d-99]{polygon-fill:rgb(230,85,13);}","#prd_crime_precinct[per1000\x3c\x3d${value}][pct!\x3d22][pct!\x3d-99]{polygon-fill:rgb(166,54,3);}"]});var locationSym=new nyc.carto.JenksSymbolizer({cartoSql:cartoSql,jenksColumn:"crime_count",baseCss:"#prd_crime_location{marker-fill-opacity:0.7;marker-line-color:#000;marker-line-width:2;marker-line-opacity:0.5;marker-placement:point;marker-type:ellipse;marker-fill:#5faee7;marker-allow-overlap:true;}",
cssRules:["#prd_crime_location[zoom\x3c14][crime_count\x3c\x3d${value}]{marker-width:5;}#prd_crime_location[zoom\x3e13][crime_count\x3c\x3d${value}]{marker-width:10;}","#prd_crime_location[zoom\x3c14][crime_count\x3c\x3d${value}]{marker-width:10;}#prd_crime_location[zoom\x3e13][crime_count\x3c\x3d${value}]{marker-width:20;}","#prd_crime_location[zoom\x3c14][crime_count\x3c\x3d${value}]{marker-width:15;}#prd_crime_location[zoom\x3e13][crime_count\x3c\x3d${value}]{marker-width:30;}","#prd_crime_location[zoom\x3c14][crime_count\x3c\x3d${value}]{marker-width:20;}#prd_crime_location[zoom\x3e13][crime_count\x3c\x3d${value}]{marker-width:40;}",
"#prd_crime_location[zoom\x3c14][crime_count\x3c\x3d${value}]{marker-width:25;}#prd_crime_location[zoom\x3e13][crime_count\x3c\x3d${value}]{marker-width:50;}"]});var heatSym=new nyc.carto.HeatSymbolizer({map:map,layer:heatLayer,css:"Map{\n"+"\t-torque-frame-count:1;\n"+"\t-torque-animation-duration:10;\n"+'\t-torque-time-attribute:"cartodb_id";\n'+'\t-torque-aggregation-function:"count(cartodb_id)";\n'+"\t-torque-resolution:2;\n"+"\t-torque-data-aggregation:linear;\n"+"}\n"+"#stg_crime_loaction{\n"+
"\timage-filters:colorize-alpha(\n"+"\t\trgba(254,237,222,0.7),\n"+"\t\trgba(253,190,133,0.7),\n"+"\t\trgba(253,141,60,0.7),\n"+"\t\trgba(230,85,13,0.7),\n"+"\t\trgba(166,54,3,0.7)\n"+"\t);\n"+"\tmarker-file:url(https://s3.amazonaws.com/com.cartodb.assets.static/alphamarker.png);\n"+"\tmarker-fill-opacity:0.4*[value];\n"+"\tmarker-width:${size};\n"+"}\n"+"#stg_crime_loaction[frame-offset\x3d1]{\n"+"marker-fill-opacity:0.2;\n"+"marker-width:${sizePlus2};\n"+"}\n"+"#stg_crime_loaction[frame-offset\x3d2]{\n"+
"marker-fill-opacity:0.1;\n"+"marker-width:${sizePlus4};\n"+"}"});var locationLeg=new nyc.BinLegend("location",nyc.BinLegend.SymbolType.POLYGON,nyc.BinLegend.BinType.RANGE_INT);var viewSwitcher=new nyc.carto.ViewSwitcher([new nyc.carto.SqlView({name:"precinct",layer:precinctLayer,sqlTemplate:precinctSql,descriptionTemplate:"\x3cb\x3e${displayType} per 1000 Residents by Precinct\x3cbr\x3e${displayDates}\x3c/b\x3e",symbolizer:precinctSym,legend:new nyc.BinLegend("precinct",nyc.BinLegend.SymbolType.POLYGON,
nyc.BinLegend.BinType.RANGE_NUMBER)}),new nyc.carto.SqlView({name:"sector",layer:sectorLayer,sqlTemplate:sectorSql,descriptionTemplate:"\x3cb\x3e${displayType} per Location\x3cbr\x3e${displayDates}\x3c/b\x3e",symbolizer:locationSym,legend:locationLeg}),new nyc.carto.SqlView({name:"location",layer:locationLayer,sqlTemplate:locationSql,descriptionTemplate:"\x3cb\x3e${displayType} per Location\x3cbr\x3e${displayDates}\x3c/b\x3e",symbolizer:locationSym,legend:locationLeg}),new nyc.carto.SqlView({name:"heat",
layer:heatLayer,sqlTemplate:heatSql,descriptionTemplate:"\x3cb\x3eConcentration of ${displayType}\x3cbr\x3e${displayDates}\x3c/b\x3e",symbolizer:heatSym,legend:new nyc.Legend('\x3ctable class\x3d"legend heat"\x3e\x3ccaption\x3e${caption}\x3c/caption\x3e\x3ctbody\x3e\x3ctr\x3e\x3ctd class\x3d"leg-bin leg-bin-0"\x3e\x3c/td\x3e\x3ctd class\x3d"leg-bin-desc"\x3eLowest Concentration\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"leg-bin leg-bin-1"\x3e\x3c/td\x3e\x3ctd class\x3d"leg-bin-desc"\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"leg-bin leg-bin-2"\x3e\x3c/td\x3e\x3ctd class\x3d"leg-bin-desc"\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"leg-bin leg-bin-3"\x3e\x3c/td\x3e\x3ctd class\x3d"leg-bin-desc"\x3e\x3c/td\x3e\x3c/tr\x3e\x3ctr\x3e\x3ctd class\x3d"leg-bin leg-bin-4"\x3e\x3c/td\x3e\x3ctd class\x3d"leg-bin-desc"\x3eHighest Concentration\x3c/td\x3e\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e')})]);
function labelLookup(lbl){var label={14:"MTS",18:"MTN",22:"CPP","-99":"DOC","Manhattan South Precinct":"MTS","Manhattan North Precinct":"MTN","Central Park Precinct":"CPP","Department of Correction":"DOC"}[lbl]||lbl;if(label.length>13&&label.indexOf("Precinct")>-1)label=label.replace(/Precinct/,"Pct.");return label}var chartDescription="\x3cdiv\x3e${displayType} per 1000 Residents\x3c/div\x3e";var allChart=new nyc.carto.Chart({cartoSql:cartoSql,canvas:"#chart-all canvas",sqlTemplate:allChartSql,descriptionTemplate:chartDescription,
dataColumn:"per1000",labelColumn:"pct",labelLookupFunction:labelLookup});var summaryChart=new nyc.carto.Chart({cartoSql:cartoSql,canvas:"#chart-sum canvas",sqlTemplate:summaryChartSql,descriptionTemplate:chartDescription,dataColumn:"per1000",labelColumn:"label",labelLookupFunction:labelLookup});var controls=new nyc.leaf.ZoomSearch(map,true);(new cartodb.SQL({user:"nycmap",format:"geoJSON"})).execute("SELECT * FROM prd_crime_precinct_list()").done(function(data){controls.setFeatures("precinct","Precinct",
"Search for a precinct...",data.features);(new cartodb.SQL({user:"nycmap",format:"geoJSON"})).execute("SELECT * FROM stg_crime_rikers_isl()").done(function(data){controls.setFeatures("correction","Department of Correction","Department of Correction",data.features);$("#mnu-srch-typ li.srch-type-correction").click(function(){$("#fld-srch li.srch-type-correction").trigger("click")})})});cartoSql.execute("SELECT * FROM stg_crime_month_range()").done(function(data){var min=data.rows[0].min_mo+"",max=data.rows[0].max_mo+
"";var dateRange=new nyc.MonthRangePicker({target:"#date-range-input",title:"Date Range",minMonth:min.substr(4,2)-1,minYear:min.substr(0,4)*1,maxMonth:max.substr(4,2)-1,maxYear:max.substr(0,4)*1});var locationMgr=new nyc.LocationMgr({controls:controls,locate:new nyc.leaf.Locate(map,new nyc.Geoclient("//maps.nyc.gov/geoclient/v1/search.json?app_key\x3dDE97954FE594D6617\x26app_id\x3dcrime-map","EPSG:4326"),nyc.leaf.EXTENT),locator:new nyc.leaf.Locator({map:map,icon:L.icon({iconUrl:"img/me0.svg",iconSize:[38,
95],iconAnchor:[22,94]}),style:function(){return{weight:10,color:"black",fill:false}}})});nyc.app=new nyc.App({map:map,viewSwitcher:viewSwitcher,locationMgr:locationMgr,mapType:mapType,crimeType:crimeType,dateRange:dateRange,allChart:allChart,summaryChart:summaryChart,locationInfo:new nyc.carto.Dao(cartoSql,"SELECT * FROM prd_crime_location_info(${lng}, ${lat})"),crimeDrillDown:{precinct:new nyc.carto.Dao(cartoSql,"SELECT * FROM prd_crime_precinct_drilldown(${min_mo}, ${max_mo}, ${pct}, ARRAY[${crime_types}])"),
sector:new nyc.carto.Dao(cartoSql,"SELECT * FROM prd_crime_sector_drilldown(${min_mo}, ${max_mo}, ${cartodb_id}, ARRAY[${crime_types}])"),location:new nyc.carto.Dao(cartoSql,"SELECT * FROM prd_crime_location_drilldown(${min_mo}, ${max_mo}, ${x}, ${y}, ARRAY[${crime_types}])")}});$("div.cartodb-logo").hide()})}$("#copyright").html("\x26copy;"+(new Date).getFullYear()+" City of New York");var map=L.map("map",{center:[40.7033127,-73.979681],zoom:10,scrollWheelZoom:true,maxZoom:nyc.leaf.ZoomSearch.MAX_ZOOM});
L.tileLayer("https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_nolabels/{z}/{x}/{y}.png").addTo(map);L.tileLayer("https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_only_labels/{z}/{x}/{y}.png").setZIndex(100).addTo(map);map.fitBounds(nyc.leaf.EXTENT);cartodb.createLayer(map,{user_name:"nycmap",type:"torque",sublayers:[{sql:"SELECT * FROM stg_crime_heat()",cartocss:"#stg_crime_heat{marker-opacity:0;}"}]},{https:true}).addTo(map).done(function(heatLayer){cartodb.createLayer(map,{user_name:"nycmap",
type:"cartodb",sublayers:[{sql:"SELECT * FROM prd_crime_precinct()",cartocss:"#prd_crime_precinct{polygon-opacity:0;}"},{sql:"SELECT * FROM prd_crime_sector()",cartocss:"#prd_crime_sector{marker-opacity:0;}"},{sql:"SELECT * FROM prd_crime_location()",cartocss:"#prd_crime_location{marker-opacity:0;}"}]},{https:true}).addTo(map).done(function(layers){layers.setInteraction(true);var precinctLayer=layers.getSubLayer(0);var sectorLayer=layers.getSubLayer(1);var locationLayer=layers.getSubLayer(2);layersLoaded(precinctLayer,
sectorLayer,locationLayer,heatLayer)})})});
//# sourceMappingURL=nyc-crime.sourcemap.json